name: fetch Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 1'
    

env:
  HUSKY_SKIP: true
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  fetchdata:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js LTS (20.x)
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: npm install
        run: npm install
      - name: Fetch Libraries
        run: npm run fetchLibraries
      - name: Process Changes
        run: npm run changes
      - name: Fetch OpenUI5 Commits
        run: npm run fetchOpenUI5Commits
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
      - name: Match Changes with Commits
        run: npm run matchChangesCommits
      - name: Parse Changes
        run: npm run parseChanges
      - name: Parse Changes Select
        run: npm run parseChangesSelect
      - name: Process Deprecated Items
        run: npm run deprecated
      - name: Fetch What's New
        run: npm run fetchWhatsNew
      - name: Create RSS Feed
        run: npm run createRSSFeed
      - name: Commit/Push build to docs branch
        run: |
          git config --global user.name 'marianfoo'
          git config --global user.email '13335743+marianfoo@users.noreply.github.com'
          git add .
          git commit -m "chore: fetch new data"
          git push origin HEAD:main